In [1]:
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
#1
ser1 = pd.Series([1, 2, 3, 4, 5])
df1=pd.DataFrame(ser1)
df1.reset_index(inplace = True)
print(df1)

   index  0
0      0  1
1      1  2
2      2  3
3      3  4
4      4  5


In [3]:
#2
ser21 = pd.Series([1, 2, 3, 4, 5])
ser22 = pd.Series([4, 5, 6, 7, 8])
df2 = pd.concat([ser21, ser22], axis=1)
df2
# we can merge in coloumn wise using axis=1

0  1
0  1  4
1  2  5
2  3  6
3  4  7
4  5  8

In [4]:
#3
ser31=pd.Series([1, 2, 3, 4, 5], index = ["one", "two", "three", "four", "five"])
ser31.index.rename("numbers")
ser31

one      1
two      2
three    3
four     4
five     5
dtype: int64

In [5]:
#4
ser41 = pd.Series([1, 2, 3, 4, 5])
ser42 = pd.Series([4, 3, 6, 7, 8])
ser43=ser41[~ser41.isin(ser42)]
ser43

0    1
1    2
4    5
dtype: int64

In [6]:
#5
ser51 = pd.Series(np.union1d(ser41, ser42))
ser52 = pd.Series(np.intersect1d(ser41, ser42))
ser53 = ser51[~ser51.isin(ser52)]
ser53

0    1
1    2
4    5
5    6
6    7
7    8
dtype: int64

In [7]:
#6
ser61=pd.Series([1, 2, 3, 4, 5, 6, 7])
ser6 = np.percentile(ser61, q=[0, 25, 50, 75, 100])
ser6

array([1. , 2.5, 4. , 5.5, 7. ])

In [8]:
#7
ser71 = pd.Series([1, 2, 3, 7, 2, 4, 8, 4, 3, 2, 1, 7, 10, 2, 7])
ser7 = ser71.value_counts()
ser7

2     4
7     3
4     2
3     2
1     2
10    1
8     1
dtype: int64

In [9]:
#8
ser7[~ser7.isin(ser7[:2])] = 'Other'
ser7

2         4
7         3
4     Other
3     Other
1     Other
10    Other
8     Other
dtype: object

In [10]:
#10
arr = np.array(np.random.randint(20, size=10))
df10 = pd.DataFrame(arr)
df10

0
0  19
1   8
2   4
3  19
4   3
5  12
6  18
7  10
8  19
9  10

In [11]:
#9
df9 = pd.qcut(np.random.randint(20, size=10), q=10)
df9

[(-0.001, 1.8], (1.8, 2.0], (4.4, 6.2], (1.8, 2.0], (14.1, 15.0], (2.7, 3.0], (2.7, 3.0], (6.2, 10.0], (3.5, 4.4], (10.0, 14.1]]
Categories (10, interval[float64]): [(-0.001, 1.8] < (1.8, 2.0] < (2.0, 2.7] < (2.7, 3.0] ... (4.4, 6.2] < (6.2, 10.0] < (10.0, 14.1] < (14.1, 15.0]]

In [12]:
#11
ser11 = pd.Series(np.random.randint(40, size = 30))
ser11 = ser11[ser11 % 3 == 0]
ser11

4     12
12     9
16     3
18    15
21    12
29    36
dtype: int32

In [13]:
#12
pos = [2, 4, 6]
ser12 = pd.Series(np.random.randint(40, size = 30))
ser12[pos]


2    30
4     7
6    18
dtype: int32

In [14]:
#13
a = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
b = np.array([[81, 72, 63, 54], [44, 35, 26, 17]])
c = np.stack((a, b), axis = 1)
d = np.stack((a, b), axis = 0)
print("horizontal stack")
print(c)
print("vertical stack")
print(d)

horizontal stack
[[[ 1  2  3  4]
  [81 72 63 54]]

 [[ 4  5  6  7]
  [44 35 26 17]]]
vertical stack
[[[ 1  2  3  4]
  [ 4  5  6  7]]

 [[81 72 63 54]
  [44 35 26 17]]]


In [15]:
#14
ser141 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8])
ser142 = pd.Series([8, 2, 1, 6, 4, 7, 10])
ser142[ser142.isin(ser141)].sort_values()

2    1
1    2
4    4
3    6
5    7
0    8
dtype: int64

In [16]:
#16
ser161 = pd.Series([2, 4, 3, 6, 7, 1, 9, 10])
ser161.diff()

0    NaN
1    2.0
2   -1.0
3    3.0
4    1.0
5   -6.0
6    8.0
7    1.0
dtype: float64

In [17]:
#17
ser171 = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
ser171 = pd.to_datetime(ser171)
ser171.dt.date

0    2010-01-01
1    2011-02-02
2    2012-03-03
3    2013-04-04
4    2014-05-05
5    2015-06-06
dtype: object

In [18]:
#18
print("Day of month \n",ser171.dt.day)
print("Week of year \n",ser171.dt.weekofyear)
print("Day of year \n",ser171.dt.dayofyear)
print("Day of week \n",ser171.dt.dayofweek)


Day of month 
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
Week of year 
 0    53
1     5
2     9
3    14
4    19
5    23
dtype: int64
Day of year 
 0      1
1     33
2     63
3     94
4    125
5    157
dtype: int64
Day of week 
 0    4
1    2
2    5
3    3
4    0
5    5
dtype: int64


In [19]:
#19
ser191 = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
ser191 = pd.Series(['4' + s for s in ser191 ])
ser191 = pd.to_datetime(ser191)
ser191


0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [20]:
#20
import regex as re
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
emails = re.findall('[a-zA-Z0-9]+[@]+[a-z0-9]+[.]+[a-z]*',str(emails))
emails

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

In [21]:
#21
ser211 = pd.Series([1, 2, 3, 4, 5])
ser212 = pd.Series([4, 3, 6, 7, 8])
dis = np.linalg.norm(ser211-ser212)
dis

6.082762530298219

In [22]:
#23
str23 = "least repeated values purd"
str23 = pd.Series(list(str23))
str23 = str23.replace(to_replace = " ", value = str23.value_counts().keys()[-1])
str23


0     l
1     e
2     a
3     s
4     t
5     v
6     r
7     e
8     p
9     e
10    a
11    t
12    e
13    d
14    v
15    v
16    a
17    l
18    u
19    e
20    s
21    v
22    p
23    u
24    r
25    d
dtype: object

In [23]:
#27
df = pd.read_csv("BostonHousing.csv")
df['age'] = df['age'] + 1
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  66.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  79.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  62.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  46.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  55.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [24]:
#28
df28 = pd.read_csv("BostonHousing.csv", usecols=[1, 3, 5, 7, 9])
df28.head()

zn  chas     rm     dis  tax
0  18.0     0  6.575  4.0900  296
1   0.0     0  6.421  4.9671  242
2   0.0     0  7.185  4.9671  242
3   0.0     0  6.998  6.0622  222
4   0.0     0  7.147  6.0622  222

In [25]:
#29
print(df[df['age'] == 101].index,df[df['age'] == 101].columns)

Int64Index([  8,  23,  31, 141, 142, 143, 145, 146, 151, 158, 159, 209, 258,
            259, 367, 368, 371, 373, 374, 379, 382, 383, 386, 388, 398, 400,
            401, 402, 405, 406, 407, 409, 410, 411, 412, 413, 414, 415, 418,
            420, 437, 442, 443],
           dtype='int64') Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [39]:
#30
df1 = df.rename(columns = {"b":"B"})
df1.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  66.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  79.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  62.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  46.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  55.2  6.0622    3  222     18.7   

        B  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [54]:
#31
df.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [64]:
#32
arr32 = np.array([[1,2,3,np.NaN], [4,6,np.NaN,2], [34,np.NaN,56,23], [2,3,4,5],[np.NaN,6,23,4]])
df32 = pd.DataFrame(arr32)
df32.isnull().sum()

0    1
1    1
2    1
3    1
dtype: int64

In [68]:
df32 = df32.fillna(df32.mean())
df32

0     1     2     3
0   1.00  2.00   3.0   8.5
1   4.00  6.00  21.5   2.0
2  34.00  4.25  56.0  23.0
3   2.00  3.00   4.0   5.0
4  10.25  6.00  23.0   4.0

In [71]:
#34
df34 = pd.DataFrame(df['age'])
type(df34)

pandas.core.frame.DataFrame

In [104]:
#35
col32 = list(df.columns)
col32 = sorted(col32)
df35 = pd.DataFrame(df, columns = col32)
df35.head()

age       b  chas     crim     dis  indus  lstat  medv    nox  ptratio  \
0  66.2  396.90     0  0.00632  4.0900   2.31   4.98  24.0  0.538     15.3   
1  79.9  396.90     0  0.02731  4.9671   7.07   9.14  21.6  0.469     17.8   
2  62.1  392.83     0  0.02729  4.9671   7.07   4.03  34.7  0.469     17.8   
3  46.8  394.63     0  0.03237  6.0622   2.18   2.94  33.4  0.458     18.7   
4  55.2  396.90     0  0.06905  6.0622   2.18   5.33  36.2  0.458     18.7   

   rad     rm  tax    zn  
0    1  6.575  296  18.0  
1    2  6.421  242   0.0  
2    2  7.185  242   0.0  
3    3  6.998  222   0.0  
4    3  7.147  222   0.0

In [115]:
#36
col36 = ['age','b','dis','zn']
df[col36].head(2)

age      b     dis    zn
0  66.2  396.9  4.0900  18.0
1  79.9  396.9  4.9671   0.0

In [128]:
#37
df37 = (df/df.sum())*100
df37.head()

crim        zn     indus  chas       nox        rm       age       dis  \
0  0.000346  0.313043  0.040992   0.0  0.191680  0.206759  0.188042  0.212988   
1  0.001494  0.000000  0.125461   0.0  0.167097  0.201917  0.226957  0.258664   
2  0.001493  0.000000  0.125461   0.0  0.167097  0.225942  0.176396  0.258664   
3  0.001770  0.000000  0.038685   0.0  0.163178  0.220061  0.132936  0.315692   
4  0.003776  0.000000  0.038685   0.0  0.163178  0.224747  0.156796  0.315692   

        rad       tax   ptratio         b     lstat      medv  
0  0.020695  0.143294  0.163838  0.219917  0.077783  0.210497  
1  0.041391  0.117153  0.190609  0.219917  0.142758  0.189447  
2  0.041391  0.117153  0.190609  0.217662  0.062945  0.304343  
3  0.062086  0.107471  0.200246  0.218659  0.045920  0.292941  
4  0.062086  0.107471  0.200246  0.219917  0.083249  0.317499

In [141]:
#38
df38 = df[df.index % 10 == 0]
df38.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0   0.00632  18.0   2.31     0  0.538  6.575  66.2  4.0900    1  296     15.3   
10  0.22489  12.5   7.87     0  0.524  6.377  95.3  6.3467    5  311     15.2   
20  1.25179   0.0   8.14     0  0.538  5.570  99.1  3.7979    4  307     21.0   
30  1.13081   0.0   8.14     0  0.538  5.713  95.1  4.2330    4  307     21.0   
40  0.03359  75.0   2.95     0  0.428  7.024  16.8  5.4011    3  252     18.3   

         b  lstat  medv  
0   396.90   4.98  24.0  
10  392.52  20.45  15.0  
20  376.57  21.02  13.6  
30  360.17  22.60  12.7  
40  395.62   1.98  34.9

In [219]:
#39
df39 = pd.read_csv("BostonHousing.csv")
df39['PK'] = df39['age'].map(str)+df39['tax'].map(str)
df39.head()


crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv       PK  
0  396.90   4.98  24.0  65.2296  
1  396.90   9.14  21.6  78.9242  
2  392.83   4.03  34.7  61.1242  
3  394.63   2.94  33.4  45.8222  
4  396.90   5.33  36.2  54.2222

In [186]:
#40
n_largest = 7
ser40 = df['tax'].drop_duplicates().nlargest(n_largest)
ser40.tail(1).index

Int64Index([342], dtype='int64')

In [187]:
#41


In [226]:
#43
df43 = pd.read_csv("BostonHousing.csv")
r1, r2 = pd.DataFrame(df43.iloc[2]).swapaxes(0,1), pd.DataFrame(df43.iloc[3]).swapaxes(0,1)
df43 = pd.concat((df43[:2],r2,r1,df43[4:]))
df43.head()

crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   ptratio       b  lstat  medv  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
3     18.7  394.63   2.94  33.4  
2     17.8  392.83   4.03  34.7  
4     18.7  396.90   5.33  36.2

In [251]:
#44
df44 = pd.read_csv("BostonHousing.csv")
enc = pd.get_dummies(df44['chas'])
enc.head()

0  1
0  1  0
1  1  0
2  1  0
3  1  0
4  1  0

In [282]:
#45
df45 = pd.read_csv("BostonHousing.csv")
m45 = df45[df45 == df45.max()].count()
m45[m45 == m45.max()].index

Index(['rad'], dtype='object')

In [284]:
#46
df46 = pd.read_csv("BostonHousing.csv")
df46 = (df46-df46.mean())/df46.std()
df46.head()

crim        zn     indus      chas       nox        rm       age  \
0 -0.419367  0.284548 -1.286636 -0.272329 -0.144075  0.413263 -0.119895   
1 -0.416927 -0.487240 -0.592794 -0.272329 -0.739530  0.194082  0.366803   
2 -0.416929 -0.487240 -0.592794 -0.272329 -0.739530  1.281446 -0.265549   
3 -0.416338 -0.487240 -1.305586 -0.272329 -0.834458  1.015298 -0.809088   
4 -0.412074 -0.487240 -1.305586 -0.272329 -0.834458  1.227362 -0.510674   

        dis       rad       tax   ptratio         b     lstat      medv  
0  0.140075 -0.981871 -0.665949 -1.457558  0.440616 -1.074499  0.159528  
1  0.556609 -0.867024 -0.986353 -0.302794  0.440616 -0.491953 -0.101424  
2  0.556609 -0.867024 -0.986353 -0.302794  0.396035 -1.207532  1.322937  
3  1.076671 -0.752178 -1.105022  0.112920  0.415751 -1.360171  1.181589  
4  1.076671 -0.752178 -1.105022  0.112920  0.440616 -1.025487  1.486032

In [298]:
#47
df47 = pd.read_csv("BostonHousing.csv")
df47 = np.fill_diagonal(df47.values, 0)
df47.head()

In [316]:
#48
df48 = pd.read_csv("BostonHousing.csv")
print(df48.groupby(by = ['chas']).get_group(0))

        crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  3

In [321]:
#49
df491 = pd.DataFrame({'numbers': [1, 2, 3, 4], 'colors': ['red', 'white', 'blue','yellow']})
df492 = pd.DataFrame({'Numbers': [1, 2, 3], 'Colors': ['red', 'yellow', 'blue']})
df49 = df492.join(df491.set_index('colors'), on = 'Colors')
df49

Numbers  Colors  numbers
0        1     red        1
1        2  yellow        4
2        3    blue        3

In [333]:
#50
df50 = pd.DataFrame(["STD, City State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])
df50.row.str.split(",",expand=True)


0                        1
0  STD               City State
1   33   Kolkata    West Bengal
2   44    Chennai    Tamil Nadu
3   40   Hyderabad    Telengana
4   80   Bangalore    Karnataka